sablecc:
	java -jar sablecc-3.2/lib/sablecc.jar minijava.grammar

all: sablecc


clean-sablecc:
	rm -rf minijava/*.class minijava/analysis minijava/lexer minijava/node minijava/parser

clean: clean-sablecc
