/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.parser;

import minijava.lexer.*;
import minijava.node.*;
import minijava.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

@SuppressWarnings("nls")
public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList nodeList;

    private final Lexer lexer;
    private final ListIterator stack = new LinkedList().listIterator();
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(@SuppressWarnings("hiding") Lexer lexer)
    {
        this.lexer = lexer;
    }

    @SuppressWarnings({"unchecked","unused"})
    private void push(int numstate, ArrayList listNode) throws ParserException, LexerException, IOException
    {
        this.nodeList = listNode;

        if(!this.stack.hasNext())
        {
            this.stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) this.stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            int middle = (low + high) / 2;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) this.stack.previous();
        this.stack.next();
        return s.state;
    }

    private ArrayList pop()
    {
        return ((State) this.stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        this.converter.index = -1;
        token.apply(this.converter);
        return this.converter.index;
    }

    @SuppressWarnings("unchecked")
    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null);
        List<Node> ign = null;
        while(true)
        {
            while(index(this.lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new LinkedList<Node>();
                }

                ign.add(this.lexer.next());
            }

            if(ign != null)
            {
                this.ignoredTokens.setIn(this.lexer.peek(), ign);
                ign = null;
            }

            this.last_pos = this.lexer.peek().getPos();
            this.last_line = this.lexer.peek().getLine();
            this.last_token = this.lexer.peek();

            int index = index(this.lexer.peek());
            this.action[0] = Parser.actionTable[state()][0][1];
            this.action[1] = Parser.actionTable[state()][0][2];

            int low = 1;
            int high = Parser.actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < Parser.actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > Parser.actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    this.action[0] = Parser.actionTable[state()][middle][1];
                    this.action[1] = Parser.actionTable[state()][middle][2];
                    break;
                }
            }

            switch(this.action[0])
            {
                case SHIFT:
		    {
		        ArrayList list = new ArrayList();
		        list.add(this.lexer.next());
                        push(this.action[1], list);
                    }
		    break;
                case REDUCE:
                    switch(this.action[1])
                    {
                    case 0: /* reduce AAprogram1Program */
		    {
			ArrayList list = new0();
			push(goTo(0), list);
		    }
		    break;
                    case 1: /* reduce AAprogram2Program */
		    {
			ArrayList list = new1();
			push(goTo(0), list);
		    }
		    break;
                    case 2: /* reduce AMainClass */
		    {
			ArrayList list = new2();
			push(goTo(1), list);
		    }
		    break;
                    case 3: /* reduce AAsimpleclassclassdecl1ClassDecl */
		    {
			ArrayList list = new3();
			push(goTo(2), list);
		    }
		    break;
                    case 4: /* reduce AAsimpleclassclassdecl2ClassDecl */
		    {
			ArrayList list = new4();
			push(goTo(2), list);
		    }
		    break;
                    case 5: /* reduce AAsimpleclassclassdecl3ClassDecl */
		    {
			ArrayList list = new5();
			push(goTo(2), list);
		    }
		    break;
                    case 6: /* reduce AAsimpleclassclassdecl4ClassDecl */
		    {
			ArrayList list = new6();
			push(goTo(2), list);
		    }
		    break;
                    case 7: /* reduce AAextendedclassclassdecl1ClassDecl */
		    {
			ArrayList list = new7();
			push(goTo(2), list);
		    }
		    break;
                    case 8: /* reduce AAextendedclassclassdecl2ClassDecl */
		    {
			ArrayList list = new8();
			push(goTo(2), list);
		    }
		    break;
                    case 9: /* reduce AAextendedclassclassdecl3ClassDecl */
		    {
			ArrayList list = new9();
			push(goTo(2), list);
		    }
		    break;
                    case 10: /* reduce AAextendedclassclassdecl4ClassDecl */
		    {
			ArrayList list = new10();
			push(goTo(2), list);
		    }
		    break;
                    case 11: /* reduce AVarDecl */
		    {
			ArrayList list = new11();
			push(goTo(3), list);
		    }
		    break;
                    case 12: /* reduce AAmethoddecl1MethodDecl */
		    {
			ArrayList list = new12();
			push(goTo(4), list);
		    }
		    break;
                    case 13: /* reduce AAmethoddecl2MethodDecl */
		    {
			ArrayList list = new13();
			push(goTo(4), list);
		    }
		    break;
                    case 14: /* reduce AAmethoddecl3MethodDecl */
		    {
			ArrayList list = new14();
			push(goTo(4), list);
		    }
		    break;
                    case 15: /* reduce AAmethoddecl4MethodDecl */
		    {
			ArrayList list = new15();
			push(goTo(4), list);
		    }
		    break;
                    case 16: /* reduce AAnotemptyformallistformallist1Formallist */
		    {
			ArrayList list = new16();
			push(goTo(5), list);
		    }
		    break;
                    case 17: /* reduce AAnotemptyformallistformallist2Formallist */
		    {
			ArrayList list = new17();
			push(goTo(5), list);
		    }
		    break;
                    case 18: /* reduce AEmptyFormallistFormallist */
		    {
			ArrayList list = new18();
			push(goTo(5), list);
		    }
		    break;
                    case 19: /* reduce AFormal */
		    {
			ArrayList list = new19();
			push(goTo(6), list);
		    }
		    break;
                    case 20: /* reduce AFormaltail */
		    {
			ArrayList list = new20();
			push(goTo(7), list);
		    }
		    break;
                    case 21: /* reduce AIntArrayTypeType */
		    {
			ArrayList list = new21();
			push(goTo(8), list);
		    }
		    break;
                    case 22: /* reduce ABooleanTypeType */
		    {
			ArrayList list = new22();
			push(goTo(8), list);
		    }
		    break;
                    case 23: /* reduce AIntTypeType */
		    {
			ArrayList list = new23();
			push(goTo(8), list);
		    }
		    break;
                    case 24: /* reduce AIdTypeType */
		    {
			ArrayList list = new24();
			push(goTo(8), list);
		    }
		    break;
                    case 25: /* reduce AStmWithoutTrailingSubstmStatement */
		    {
			ArrayList list = new25();
			push(goTo(9), list);
		    }
		    break;
                    case 26: /* reduce AIfStatement */
		    {
			ArrayList list = new26();
			push(goTo(9), list);
		    }
		    break;
                    case 27: /* reduce AIfElseStatement */
		    {
			ArrayList list = new27();
			push(goTo(9), list);
		    }
		    break;
                    case 28: /* reduce AWhileStatement */
		    {
			ArrayList list = new28();
			push(goTo(9), list);
		    }
		    break;
                    case 29: /* reduce AAblockstmwithouttrailingsubstm1StmWithoutTrailingSubstm */
		    {
			ArrayList list = new29();
			push(goTo(10), list);
		    }
		    break;
                    case 30: /* reduce AAblockstmwithouttrailingsubstm2StmWithoutTrailingSubstm */
		    {
			ArrayList list = new30();
			push(goTo(10), list);
		    }
		    break;
                    case 31: /* reduce APrintStmWithoutTrailingSubstm */
		    {
			ArrayList list = new31();
			push(goTo(10), list);
		    }
		    break;
                    case 32: /* reduce AAssignStmWithoutTrailingSubstm */
		    {
			ArrayList list = new32();
			push(goTo(10), list);
		    }
		    break;
                    case 33: /* reduce AArrayassignStmWithoutTrailingSubstm */
		    {
			ArrayList list = new33();
			push(goTo(10), list);
		    }
		    break;
                    case 34: /* reduce AStmWithoutTrailingSubstmStmNoShortIf */
		    {
			ArrayList list = new34();
			push(goTo(11), list);
		    }
		    break;
                    case 35: /* reduce AWhileNoShortIfStmNoShortIf */
		    {
			ArrayList list = new35();
			push(goTo(11), list);
		    }
		    break;
                    case 36: /* reduce AIfElseNoShortIfStmNoShortIf */
		    {
			ArrayList list = new36();
			push(goTo(11), list);
		    }
		    break;
                    case 37: /* reduce AAndExp */
		    {
			ArrayList list = new37();
			push(goTo(12), list);
		    }
		    break;
                    case 38: /* reduce ALessExpExp */
		    {
			ArrayList list = new38();
			push(goTo(12), list);
		    }
		    break;
                    case 39: /* reduce ALessLessExp */
		    {
			ArrayList list = new39();
			push(goTo(13), list);
		    }
		    break;
                    case 40: /* reduce AAddsubExpLessExp */
		    {
			ArrayList list = new40();
			push(goTo(13), list);
		    }
		    break;
                    case 41: /* reduce APlusAddsubExp */
		    {
			ArrayList list = new41();
			push(goTo(14), list);
		    }
		    break;
                    case 42: /* reduce AMinusAddsubExp */
		    {
			ArrayList list = new42();
			push(goTo(14), list);
		    }
		    break;
                    case 43: /* reduce AMulExpAddsubExp */
		    {
			ArrayList list = new43();
			push(goTo(14), list);
		    }
		    break;
                    case 44: /* reduce ATimesMulExp */
		    {
			ArrayList list = new44();
			push(goTo(15), list);
		    }
		    break;
                    case 45: /* reduce ANotExpMulExp */
		    {
			ArrayList list = new45();
			push(goTo(15), list);
		    }
		    break;
                    case 46: /* reduce ANotExpNotExp */
		    {
			ArrayList list = new46();
			push(goTo(16), list);
		    }
		    break;
                    case 47: /* reduce ADotExpNotExp */
		    {
			ArrayList list = new47();
			push(goTo(16), list);
		    }
		    break;
                    case 48: /* reduce ALengthDotExp */
		    {
			ArrayList list = new48();
			push(goTo(17), list);
		    }
		    break;
                    case 49: /* reduce ACallDotExp */
		    {
			ArrayList list = new49();
			push(goTo(17), list);
		    }
		    break;
                    case 50: /* reduce AArrayExpDotExp */
		    {
			ArrayList list = new50();
			push(goTo(17), list);
		    }
		    break;
                    case 51: /* reduce AArrayArrayExp */
		    {
			ArrayList list = new51();
			push(goTo(18), list);
		    }
		    break;
                    case 52: /* reduce AFinalExpArrayExp */
		    {
			ArrayList list = new52();
			push(goTo(18), list);
		    }
		    break;
                    case 53: /* reduce AIntegerLiteralFinalExp */
		    {
			ArrayList list = new53();
			push(goTo(19), list);
		    }
		    break;
                    case 54: /* reduce ATrueFinalExp */
		    {
			ArrayList list = new54();
			push(goTo(19), list);
		    }
		    break;
                    case 55: /* reduce AFalseFinalExp */
		    {
			ArrayList list = new55();
			push(goTo(19), list);
		    }
		    break;
                    case 56: /* reduce AIdFinalExp */
		    {
			ArrayList list = new56();
			push(goTo(19), list);
		    }
		    break;
                    case 57: /* reduce AThisFinalExp */
		    {
			ArrayList list = new57();
			push(goTo(19), list);
		    }
		    break;
                    case 58: /* reduce ANewIntArrayFinalExp */
		    {
			ArrayList list = new58();
			push(goTo(19), list);
		    }
		    break;
                    case 59: /* reduce ANewIdFinalExp */
		    {
			ArrayList list = new59();
			push(goTo(19), list);
		    }
		    break;
                    case 60: /* reduce AParenExprFinalExp */
		    {
			ArrayList list = new60();
			push(goTo(19), list);
		    }
		    break;
                    case 61: /* reduce AAexplistexplist1Explist */
		    {
			ArrayList list = new61();
			push(goTo(20), list);
		    }
		    break;
                    case 62: /* reduce AAexplistexplist2Explist */
		    {
			ArrayList list = new62();
			push(goTo(20), list);
		    }
		    break;
                    case 63: /* reduce ABlankExplistExplist */
		    {
			ArrayList list = new63();
			push(goTo(20), list);
		    }
		    break;
                    case 64: /* reduce AExprest */
		    {
			ArrayList list = new64();
			push(goTo(21), list);
		    }
		    break;
                    case 65: /* reduce ATerminal$ClassDecl */
		    {
			ArrayList list = new65();
			push(goTo(22), list);
		    }
		    break;
                    case 66: /* reduce ANonTerminal$ClassDecl */
		    {
			ArrayList list = new66();
			push(goTo(22), list);
		    }
		    break;
                    case 67: /* reduce ATerminal$VarDecl */
		    {
			ArrayList list = new67();
			push(goTo(23), list);
		    }
		    break;
                    case 68: /* reduce ANonTerminal$VarDecl */
		    {
			ArrayList list = new68();
			push(goTo(23), list);
		    }
		    break;
                    case 69: /* reduce ATerminal$MethodDecl */
		    {
			ArrayList list = new69();
			push(goTo(24), list);
		    }
		    break;
                    case 70: /* reduce ANonTerminal$MethodDecl */
		    {
			ArrayList list = new70();
			push(goTo(24), list);
		    }
		    break;
                    case 71: /* reduce ATerminal$Statement */
		    {
			ArrayList list = new71();
			push(goTo(25), list);
		    }
		    break;
                    case 72: /* reduce ANonTerminal$Statement */
		    {
			ArrayList list = new72();
			push(goTo(25), list);
		    }
		    break;
                    case 73: /* reduce ATerminal$Formaltail */
		    {
			ArrayList list = new73();
			push(goTo(26), list);
		    }
		    break;
                    case 74: /* reduce ANonTerminal$Formaltail */
		    {
			ArrayList list = new74();
			push(goTo(26), list);
		    }
		    break;
                    case 75: /* reduce ATerminal$Exprest */
		    {
			ArrayList list = new75();
			push(goTo(27), list);
		    }
		    break;
                    case 76: /* reduce ANonTerminal$Exprest */
		    {
			ArrayList list = new76();
			push(goTo(27), list);
		    }
		    break;
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) this.lexer.next();
                        PProgram node1 = (PProgram) pop().get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(this.last_token,
                        "[" + this.last_line + "," + this.last_pos + "] " +
                        Parser.errorMessages[Parser.errors[this.action[1]]]);
            }
        }
    }



    @SuppressWarnings("unchecked")
    ArrayList new0() /* reduce AAprogram1Program */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PProgram pprogramNode1;
        {
            // Block
        PMainClass pmainclassNode2;
        LinkedList listNode3 = new LinkedList();
        pmainclassNode2 = (PMainClass)nodeArrayList1.get(0);
        {
            // Block
        }

        pprogramNode1 = new AProgram(pmainclassNode2, listNode3);
        }
	nodeList.add(pprogramNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new1() /* reduce AAprogram2Program */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PProgram pprogramNode1;
        {
            // Block
        PMainClass pmainclassNode2;
        LinkedList listNode4 = new LinkedList();
        pmainclassNode2 = (PMainClass)nodeArrayList1.get(0);
        {
            // Block
        LinkedList listNode3 = new LinkedList();
        listNode3 = (LinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pprogramNode1 = new AProgram(pmainclassNode2, listNode4);
        }
	nodeList.add(pprogramNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new2() /* reduce AMainClass */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList15 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList14 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList13 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList12 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList11 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList10 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList9 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PMainClass pmainclassNode1;
        {
            // Block
        TId tidNode2;
        TId tidNode3;
        PStatement pstatementNode4;
        tidNode2 = (TId)nodeArrayList2.get(0);
        tidNode3 = (TId)nodeArrayList10.get(0);
        pstatementNode4 = (PStatement)nodeArrayList13.get(0);

        pmainclassNode1 = new AMainClass(tidNode2, tidNode3, pstatementNode4);
        }
	nodeList.add(pmainclassNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new3() /* reduce AAsimpleclassclassdecl1ClassDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PClassDecl pclassdeclNode1;
        {
            // Block
        TId tidNode2;
        LinkedList listNode3 = new LinkedList();
        LinkedList listNode4 = new LinkedList();
        tidNode2 = (TId)nodeArrayList2.get(0);
        {
            // Block
        }
        {
            // Block
        }

        pclassdeclNode1 = new AClassDeclSimpleClassDecl(tidNode2, listNode3, listNode4);
        }
	nodeList.add(pclassdeclNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new4() /* reduce AAsimpleclassclassdecl2ClassDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PClassDecl pclassdeclNode1;
        {
            // Block
        TId tidNode2;
        LinkedList listNode4 = new LinkedList();
        LinkedList listNode5 = new LinkedList();
        tidNode2 = (TId)nodeArrayList2.get(0);
        {
            // Block
        LinkedList listNode3 = new LinkedList();
        listNode3 = (LinkedList)nodeArrayList4.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }
        {
            // Block
        }

        pclassdeclNode1 = new AClassDeclSimpleClassDecl(tidNode2, listNode4, listNode5);
        }
	nodeList.add(pclassdeclNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new5() /* reduce AAsimpleclassclassdecl3ClassDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PClassDecl pclassdeclNode1;
        {
            // Block
        TId tidNode2;
        LinkedList listNode3 = new LinkedList();
        LinkedList listNode5 = new LinkedList();
        tidNode2 = (TId)nodeArrayList2.get(0);
        {
            // Block
        }
        {
            // Block
        LinkedList listNode4 = new LinkedList();
        listNode4 = (LinkedList)nodeArrayList4.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }

        pclassdeclNode1 = new AClassDeclSimpleClassDecl(tidNode2, listNode3, listNode5);
        }
	nodeList.add(pclassdeclNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new6() /* reduce AAsimpleclassclassdecl4ClassDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PClassDecl pclassdeclNode1;
        {
            // Block
        TId tidNode2;
        LinkedList listNode4 = new LinkedList();
        LinkedList listNode6 = new LinkedList();
        tidNode2 = (TId)nodeArrayList2.get(0);
        {
            // Block
        LinkedList listNode3 = new LinkedList();
        listNode3 = (LinkedList)nodeArrayList4.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }
        {
            // Block
        LinkedList listNode5 = new LinkedList();
        listNode5 = (LinkedList)nodeArrayList5.get(0);
	if(listNode5 != null)
	{
	  listNode6.addAll(listNode5);
	}
        }

        pclassdeclNode1 = new AClassDeclSimpleClassDecl(tidNode2, listNode4, listNode6);
        }
	nodeList.add(pclassdeclNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new7() /* reduce AAextendedclassclassdecl1ClassDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PClassDecl pclassdeclNode1;
        {
            // Block
        TId tidNode2;
        TId tidNode3;
        LinkedList listNode4 = new LinkedList();
        LinkedList listNode5 = new LinkedList();
        tidNode2 = (TId)nodeArrayList2.get(0);
        tidNode3 = (TId)nodeArrayList4.get(0);
        {
            // Block
        }
        {
            // Block
        }

        pclassdeclNode1 = new AClassDeclExtendsClassDecl(tidNode2, tidNode3, listNode4, listNode5);
        }
	nodeList.add(pclassdeclNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new8() /* reduce AAextendedclassclassdecl2ClassDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PClassDecl pclassdeclNode1;
        {
            // Block
        TId tidNode2;
        TId tidNode3;
        LinkedList listNode5 = new LinkedList();
        LinkedList listNode6 = new LinkedList();
        tidNode2 = (TId)nodeArrayList2.get(0);
        tidNode3 = (TId)nodeArrayList4.get(0);
        {
            // Block
        LinkedList listNode4 = new LinkedList();
        listNode4 = (LinkedList)nodeArrayList6.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }
        {
            // Block
        }

        pclassdeclNode1 = new AClassDeclExtendsClassDecl(tidNode2, tidNode3, listNode5, listNode6);
        }
	nodeList.add(pclassdeclNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new9() /* reduce AAextendedclassclassdecl3ClassDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PClassDecl pclassdeclNode1;
        {
            // Block
        TId tidNode2;
        TId tidNode3;
        LinkedList listNode4 = new LinkedList();
        LinkedList listNode6 = new LinkedList();
        tidNode2 = (TId)nodeArrayList2.get(0);
        tidNode3 = (TId)nodeArrayList4.get(0);
        {
            // Block
        }
        {
            // Block
        LinkedList listNode5 = new LinkedList();
        listNode5 = (LinkedList)nodeArrayList6.get(0);
	if(listNode5 != null)
	{
	  listNode6.addAll(listNode5);
	}
        }

        pclassdeclNode1 = new AClassDeclExtendsClassDecl(tidNode2, tidNode3, listNode4, listNode6);
        }
	nodeList.add(pclassdeclNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new10() /* reduce AAextendedclassclassdecl4ClassDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PClassDecl pclassdeclNode1;
        {
            // Block
        TId tidNode2;
        TId tidNode3;
        LinkedList listNode5 = new LinkedList();
        LinkedList listNode7 = new LinkedList();
        tidNode2 = (TId)nodeArrayList2.get(0);
        tidNode3 = (TId)nodeArrayList4.get(0);
        {
            // Block
        LinkedList listNode4 = new LinkedList();
        listNode4 = (LinkedList)nodeArrayList6.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }
        {
            // Block
        LinkedList listNode6 = new LinkedList();
        listNode6 = (LinkedList)nodeArrayList7.get(0);
	if(listNode6 != null)
	{
	  listNode7.addAll(listNode6);
	}
        }

        pclassdeclNode1 = new AClassDeclExtendsClassDecl(tidNode2, tidNode3, listNode5, listNode7);
        }
	nodeList.add(pclassdeclNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new11() /* reduce AVarDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PVarDecl pvardeclNode1;
        {
            // Block
        PType ptypeNode2;
        TId tidNode3;
        ptypeNode2 = (PType)nodeArrayList1.get(0);
        tidNode3 = (TId)nodeArrayList2.get(0);

        pvardeclNode1 = new AVarDecl(ptypeNode2, tidNode3);
        }
	nodeList.add(pvardeclNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new12() /* reduce AAmethoddecl1MethodDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList11 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList10 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList9 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PMethodDecl pmethoddeclNode1;
        {
            // Block
        PType ptypeNode2;
        TId tidNode3;
        LinkedList listNode5 = new LinkedList();
        LinkedList listNode6 = new LinkedList();
        LinkedList listNode7 = new LinkedList();
        PExp pexpNode8;
        ptypeNode2 = (PType)nodeArrayList2.get(0);
        tidNode3 = (TId)nodeArrayList3.get(0);
        {
            // Block
        LinkedList listNode4 = new LinkedList();
        listNode4 = (LinkedList)nodeArrayList5.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }
        {
            // Block
        }
        {
            // Block
        }
        pexpNode8 = (PExp)nodeArrayList9.get(0);

        pmethoddeclNode1 = new AMethodDecl(ptypeNode2, tidNode3, listNode5, listNode6, listNode7, pexpNode8);
        }
	nodeList.add(pmethoddeclNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new13() /* reduce AAmethoddecl2MethodDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList12 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList11 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList10 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList9 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PMethodDecl pmethoddeclNode1;
        {
            // Block
        PType ptypeNode2;
        TId tidNode3;
        LinkedList listNode5 = new LinkedList();
        LinkedList listNode7 = new LinkedList();
        LinkedList listNode8 = new LinkedList();
        PExp pexpNode9;
        ptypeNode2 = (PType)nodeArrayList2.get(0);
        tidNode3 = (TId)nodeArrayList3.get(0);
        {
            // Block
        LinkedList listNode4 = new LinkedList();
        listNode4 = (LinkedList)nodeArrayList5.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }
        {
            // Block
        LinkedList listNode6 = new LinkedList();
        listNode6 = (LinkedList)nodeArrayList8.get(0);
	if(listNode6 != null)
	{
	  listNode7.addAll(listNode6);
	}
        }
        {
            // Block
        }
        pexpNode9 = (PExp)nodeArrayList10.get(0);

        pmethoddeclNode1 = new AMethodDecl(ptypeNode2, tidNode3, listNode5, listNode7, listNode8, pexpNode9);
        }
	nodeList.add(pmethoddeclNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new14() /* reduce AAmethoddecl3MethodDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList12 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList11 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList10 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList9 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PMethodDecl pmethoddeclNode1;
        {
            // Block
        PType ptypeNode2;
        TId tidNode3;
        LinkedList listNode5 = new LinkedList();
        LinkedList listNode6 = new LinkedList();
        LinkedList listNode8 = new LinkedList();
        PExp pexpNode9;
        ptypeNode2 = (PType)nodeArrayList2.get(0);
        tidNode3 = (TId)nodeArrayList3.get(0);
        {
            // Block
        LinkedList listNode4 = new LinkedList();
        listNode4 = (LinkedList)nodeArrayList5.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }
        {
            // Block
        }
        {
            // Block
        LinkedList listNode7 = new LinkedList();
        listNode7 = (LinkedList)nodeArrayList8.get(0);
	if(listNode7 != null)
	{
	  listNode8.addAll(listNode7);
	}
        }
        pexpNode9 = (PExp)nodeArrayList10.get(0);

        pmethoddeclNode1 = new AMethodDecl(ptypeNode2, tidNode3, listNode5, listNode6, listNode8, pexpNode9);
        }
	nodeList.add(pmethoddeclNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new15() /* reduce AAmethoddecl4MethodDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList13 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList12 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList11 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList10 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList9 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PMethodDecl pmethoddeclNode1;
        {
            // Block
        PType ptypeNode2;
        TId tidNode3;
        LinkedList listNode5 = new LinkedList();
        LinkedList listNode7 = new LinkedList();
        LinkedList listNode9 = new LinkedList();
        PExp pexpNode10;
        ptypeNode2 = (PType)nodeArrayList2.get(0);
        tidNode3 = (TId)nodeArrayList3.get(0);
        {
            // Block
        LinkedList listNode4 = new LinkedList();
        listNode4 = (LinkedList)nodeArrayList5.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }
        {
            // Block
        LinkedList listNode6 = new LinkedList();
        listNode6 = (LinkedList)nodeArrayList8.get(0);
	if(listNode6 != null)
	{
	  listNode7.addAll(listNode6);
	}
        }
        {
            // Block
        LinkedList listNode8 = new LinkedList();
        listNode8 = (LinkedList)nodeArrayList9.get(0);
	if(listNode8 != null)
	{
	  listNode9.addAll(listNode8);
	}
        }
        pexpNode10 = (PExp)nodeArrayList11.get(0);

        pmethoddeclNode1 = new AMethodDecl(ptypeNode2, tidNode3, listNode5, listNode7, listNode9, pexpNode10);
        }
	nodeList.add(pmethoddeclNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new16() /* reduce AAnotemptyformallistformallist1Formallist */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        PFormal pformalNode1;
        pformalNode1 = (PFormal)nodeArrayList1.get(0);
	if(pformalNode1 != null)
	{
	  listNode2.add(pformalNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new17() /* reduce AAnotemptyformallistformallist2Formallist */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        PFormal pformalNode1;
        LinkedList listNode2 = new LinkedList();
        pformalNode1 = (PFormal)nodeArrayList1.get(0);
        listNode2 = (LinkedList)nodeArrayList2.get(0);
	if(pformalNode1 != null)
	{
	  listNode3.add(pformalNode1);
	}
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new18() /* reduce AEmptyFormallistFormallist */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        LinkedList listNode1 = new LinkedList();
        {
            // Block
        }
	nodeList.add(listNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new19() /* reduce AFormal */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PFormal pformalNode1;
        {
            // Block
        PType ptypeNode2;
        TId tidNode3;
        ptypeNode2 = (PType)nodeArrayList1.get(0);
        tidNode3 = (TId)nodeArrayList2.get(0);

        pformalNode1 = new AFormal(ptypeNode2, tidNode3);
        }
	nodeList.add(pformalNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new20() /* reduce AFormaltail */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PFormal pformalNode1;
        {
            // Block
        PType ptypeNode2;
        TId tidNode3;
        ptypeNode2 = (PType)nodeArrayList2.get(0);
        tidNode3 = (TId)nodeArrayList3.get(0);

        pformalNode1 = new AFormal(ptypeNode2, tidNode3);
        }
	nodeList.add(pformalNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new21() /* reduce AIntArrayTypeType */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PType ptypeNode1;
        {
            // Block

        ptypeNode1 = new AIntArrayTypeType();
        }
	nodeList.add(ptypeNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new22() /* reduce ABooleanTypeType */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PType ptypeNode1;
        {
            // Block

        ptypeNode1 = new ABooleanTypeType();
        }
	nodeList.add(ptypeNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new23() /* reduce AIntTypeType */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PType ptypeNode1;
        {
            // Block

        ptypeNode1 = new AIntegerTypeType();
        }
	nodeList.add(ptypeNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new24() /* reduce AIdTypeType */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PType ptypeNode1;
        {
            // Block
        TId tidNode2;
        tidNode2 = (TId)nodeArrayList1.get(0);

        ptypeNode1 = new AIdentifierTypeType(tidNode2);
        }
	nodeList.add(ptypeNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new25() /* reduce AStmWithoutTrailingSubstmStatement */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStatement pstatementNode1;
        pstatementNode1 = (PStatement)nodeArrayList1.get(0);
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new26() /* reduce AIfStatement */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        PExp pexpNode2;
        PStatement pstatementNode3;
        pexpNode2 = (PExp)nodeArrayList3.get(0);
        pstatementNode3 = (PStatement)nodeArrayList5.get(0);

        pstatementNode1 = new AIfStatement(pexpNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new27() /* reduce AIfElseStatement */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        PExp pexpNode2;
        PStatement pstatementNode3;
        PStatement pstatementNode4;
        pexpNode2 = (PExp)nodeArrayList3.get(0);
        pstatementNode3 = (PStatement)nodeArrayList5.get(0);
        pstatementNode4 = (PStatement)nodeArrayList7.get(0);

        pstatementNode1 = new AIfElseStatement(pexpNode2, pstatementNode3, pstatementNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new28() /* reduce AWhileStatement */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        PExp pexpNode2;
        PStatement pstatementNode3;
        pexpNode2 = (PExp)nodeArrayList3.get(0);
        pstatementNode3 = (PStatement)nodeArrayList5.get(0);

        pstatementNode1 = new AWhileStatement(pexpNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new29() /* reduce AAblockstmwithouttrailingsubstm1StmWithoutTrailingSubstm */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        }

        pstatementNode1 = new ABlockStatement(listNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new30() /* reduce AAblockstmwithouttrailingsubstm2StmWithoutTrailingSubstm */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        LinkedList listNode2 = new LinkedList();
        listNode2 = (LinkedList)nodeArrayList2.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        pstatementNode1 = new ABlockStatement(listNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new31() /* reduce APrintStmWithoutTrailingSubstm */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        PExp pexpNode2;
        pexpNode2 = (PExp)nodeArrayList3.get(0);

        pstatementNode1 = new APrintStatement(pexpNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new32() /* reduce AAssignStmWithoutTrailingSubstm */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        TId tidNode2;
        PExp pexpNode3;
        tidNode2 = (TId)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList3.get(0);

        pstatementNode1 = new AAssignStatement(tidNode2, pexpNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new33() /* reduce AArrayassignStmWithoutTrailingSubstm */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        TId tidNode2;
        PExp pexpNode3;
        PExp pexpNode4;
        tidNode2 = (TId)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList3.get(0);
        pexpNode4 = (PExp)nodeArrayList6.get(0);

        pstatementNode1 = new AArrayAssignStatement(tidNode2, pexpNode3, pexpNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new34() /* reduce AStmWithoutTrailingSubstmStmNoShortIf */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStatement pstatementNode1;
        pstatementNode1 = (PStatement)nodeArrayList1.get(0);
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new35() /* reduce AWhileNoShortIfStmNoShortIf */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        PExp pexpNode2;
        PStatement pstatementNode3;
        pexpNode2 = (PExp)nodeArrayList3.get(0);
        pstatementNode3 = (PStatement)nodeArrayList5.get(0);

        pstatementNode1 = new AWhileStatement(pexpNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new36() /* reduce AIfElseNoShortIfStmNoShortIf */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        PExp pexpNode2;
        PStatement pstatementNode3;
        PStatement pstatementNode4;
        pexpNode2 = (PExp)nodeArrayList3.get(0);
        pstatementNode3 = (PStatement)nodeArrayList5.get(0);
        pstatementNode4 = (PStatement)nodeArrayList7.get(0);

        pstatementNode1 = new AIfElseStatement(pexpNode2, pstatementNode3, pstatementNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new37() /* reduce AAndExp */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        PExp pexpNode3;
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList3.get(0);

        pexpNode1 = new AAndExp(pexpNode2, pexpNode3);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new38() /* reduce ALessExpExp */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        pexpNode1 = (PExp)nodeArrayList1.get(0);
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new39() /* reduce ALessLessExp */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        PExp pexpNode3;
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList3.get(0);

        pexpNode1 = new ALessthanExp(pexpNode2, pexpNode3);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new40() /* reduce AAddsubExpLessExp */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        pexpNode1 = (PExp)nodeArrayList1.get(0);
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new41() /* reduce APlusAddsubExp */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        PExp pexpNode3;
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList3.get(0);

        pexpNode1 = new APlusExp(pexpNode2, pexpNode3);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new42() /* reduce AMinusAddsubExp */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        PExp pexpNode3;
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList3.get(0);

        pexpNode1 = new AMinusExp(pexpNode2, pexpNode3);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new43() /* reduce AMulExpAddsubExp */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        pexpNode1 = (PExp)nodeArrayList1.get(0);
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new44() /* reduce ATimesMulExp */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        PExp pexpNode3;
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList3.get(0);

        pexpNode1 = new ATimesExp(pexpNode2, pexpNode3);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new45() /* reduce ANotExpMulExp */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        pexpNode1 = (PExp)nodeArrayList1.get(0);
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new46() /* reduce ANotExpNotExp */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        pexpNode2 = (PExp)nodeArrayList2.get(0);

        pexpNode1 = new ANotExp(pexpNode2);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new47() /* reduce ADotExpNotExp */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        pexpNode1 = (PExp)nodeArrayList1.get(0);
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new48() /* reduce ALengthDotExp */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        pexpNode2 = (PExp)nodeArrayList1.get(0);

        pexpNode1 = new AArraylengthExp(pexpNode2);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new49() /* reduce ACallDotExp */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        TId tidNode3;
        LinkedList listNode5 = new LinkedList();
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        tidNode3 = (TId)nodeArrayList3.get(0);
        {
            // Block
        LinkedList listNode4 = new LinkedList();
        listNode4 = (LinkedList)nodeArrayList5.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }

        pexpNode1 = new ACallExp(pexpNode2, tidNode3, listNode5);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new50() /* reduce AArrayExpDotExp */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        pexpNode1 = (PExp)nodeArrayList1.get(0);
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new51() /* reduce AArrayArrayExp */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        PExp pexpNode3;
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList3.get(0);

        pexpNode1 = new AArraylookupExp(pexpNode2, pexpNode3);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new52() /* reduce AFinalExpArrayExp */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        pexpNode1 = (PExp)nodeArrayList1.get(0);
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new53() /* reduce AIntegerLiteralFinalExp */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        TInteger tintegerNode2;
        tintegerNode2 = (TInteger)nodeArrayList1.get(0);

        pexpNode1 = new AIntegerliteralExp(tintegerNode2);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new54() /* reduce ATrueFinalExp */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block

        pexpNode1 = new ATrueExp();
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new55() /* reduce AFalseFinalExp */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block

        pexpNode1 = new AFalseExp();
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new56() /* reduce AIdFinalExp */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        TId tidNode2;
        tidNode2 = (TId)nodeArrayList1.get(0);

        pexpNode1 = new AIdentifierexpExp(tidNode2);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new57() /* reduce AThisFinalExp */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block

        pexpNode1 = new AThisExp();
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new58() /* reduce ANewIntArrayFinalExp */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        pexpNode2 = (PExp)nodeArrayList4.get(0);

        pexpNode1 = new ANewarrayExp(pexpNode2);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new59() /* reduce ANewIdFinalExp */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        TId tidNode2;
        tidNode2 = (TId)nodeArrayList2.get(0);

        pexpNode1 = new ANewobjectExp(tidNode2);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new60() /* reduce AParenExprFinalExp */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        pexpNode1 = (PExp)nodeArrayList2.get(0);
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new61() /* reduce AAexplistexplist1Explist */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        PExp pexpNode1;
        pexpNode1 = (PExp)nodeArrayList1.get(0);
	if(pexpNode1 != null)
	{
	  listNode2.add(pexpNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new62() /* reduce AAexplistexplist2Explist */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        PExp pexpNode1;
        LinkedList listNode2 = new LinkedList();
        pexpNode1 = (PExp)nodeArrayList1.get(0);
        listNode2 = (LinkedList)nodeArrayList2.get(0);
	if(pexpNode1 != null)
	{
	  listNode3.add(pexpNode1);
	}
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new63() /* reduce ABlankExplistExplist */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        LinkedList listNode1 = new LinkedList();
        {
            // Block
        }
	nodeList.add(listNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new64() /* reduce AExprest */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        pexpNode1 = (PExp)nodeArrayList2.get(0);
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new65() /* reduce ATerminal$ClassDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        PClassDecl pclassdeclNode1;
        pclassdeclNode1 = (PClassDecl)nodeArrayList1.get(0);
	if(pclassdeclNode1 != null)
	{
	  listNode2.add(pclassdeclNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new66() /* reduce ANonTerminal$ClassDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        LinkedList listNode1 = new LinkedList();
        PClassDecl pclassdeclNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pclassdeclNode2 = (PClassDecl)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pclassdeclNode2 != null)
	{
	  listNode3.add(pclassdeclNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new67() /* reduce ATerminal$VarDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        PVarDecl pvardeclNode1;
        pvardeclNode1 = (PVarDecl)nodeArrayList1.get(0);
	if(pvardeclNode1 != null)
	{
	  listNode2.add(pvardeclNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new68() /* reduce ANonTerminal$VarDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        LinkedList listNode1 = new LinkedList();
        PVarDecl pvardeclNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pvardeclNode2 = (PVarDecl)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pvardeclNode2 != null)
	{
	  listNode3.add(pvardeclNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new69() /* reduce ATerminal$MethodDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        PMethodDecl pmethoddeclNode1;
        pmethoddeclNode1 = (PMethodDecl)nodeArrayList1.get(0);
	if(pmethoddeclNode1 != null)
	{
	  listNode2.add(pmethoddeclNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new70() /* reduce ANonTerminal$MethodDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        LinkedList listNode1 = new LinkedList();
        PMethodDecl pmethoddeclNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pmethoddeclNode2 = (PMethodDecl)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pmethoddeclNode2 != null)
	{
	  listNode3.add(pmethoddeclNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new71() /* reduce ATerminal$Statement */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        PStatement pstatementNode1;
        pstatementNode1 = (PStatement)nodeArrayList1.get(0);
	if(pstatementNode1 != null)
	{
	  listNode2.add(pstatementNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new72() /* reduce ANonTerminal$Statement */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        LinkedList listNode1 = new LinkedList();
        PStatement pstatementNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pstatementNode2 = (PStatement)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pstatementNode2 != null)
	{
	  listNode3.add(pstatementNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new73() /* reduce ATerminal$Formaltail */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        PFormal pformalNode1;
        pformalNode1 = (PFormal)nodeArrayList1.get(0);
	if(pformalNode1 != null)
	{
	  listNode2.add(pformalNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new74() /* reduce ANonTerminal$Formaltail */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        LinkedList listNode1 = new LinkedList();
        PFormal pformalNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pformalNode2 = (PFormal)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pformalNode2 != null)
	{
	  listNode3.add(pformalNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new75() /* reduce ATerminal$Exprest */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        PExp pexpNode1;
        pexpNode1 = (PExp)nodeArrayList1.get(0);
	if(pexpNode1 != null)
	{
	  listNode2.add(pexpNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new76() /* reduce ANonTerminal$Exprest */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        LinkedList listNode1 = new LinkedList();
        PExp pexpNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pexpNode2 = (PExp)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pexpNode2 != null)
	{
	  listNode3.add(pexpNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, ERROR, 0}, {0, SHIFT, 1}, },
			{{-1, ERROR, 1}, {26, SHIFT, 4}, },
			{{-1, ERROR, 2}, {35, ACCEPT, -1}, },
			{{-1, REDUCE, 0}, {0, SHIFT, 5}, },
			{{-1, ERROR, 4}, {22, SHIFT, 8}, },
			{{-1, ERROR, 5}, {26, SHIFT, 9}, },
			{{-1, REDUCE, 65}, },
			{{-1, REDUCE, 1}, {0, SHIFT, 5}, },
			{{-1, ERROR, 8}, {3, SHIFT, 11}, },
			{{-1, ERROR, 9}, {2, SHIFT, 12}, {22, SHIFT, 13}, },
			{{-1, REDUCE, 66}, },
			{{-1, ERROR, 11}, {1, SHIFT, 14}, },
			{{-1, ERROR, 12}, {26, SHIFT, 15}, },
			{{-1, ERROR, 13}, {3, SHIFT, 16}, {8, SHIFT, 17}, {9, SHIFT, 18}, {23, SHIFT, 19}, {26, SHIFT, 20}, },
			{{-1, ERROR, 14}, {24, SHIFT, 26}, },
			{{-1, ERROR, 15}, {22, SHIFT, 27}, },
			{{-1, ERROR, 16}, {8, SHIFT, 17}, {9, SHIFT, 18}, {26, SHIFT, 20}, },
			{{-1, REDUCE, 23}, {20, SHIFT, 29}, },
			{{-1, REDUCE, 22}, },
			{{-1, REDUCE, 3}, },
			{{-1, REDUCE, 24}, },
			{{-1, REDUCE, 67}, },
			{{-1, REDUCE, 69}, },
			{{-1, ERROR, 23}, {26, SHIFT, 30}, },
			{{-1, ERROR, 24}, {3, SHIFT, 16}, {8, SHIFT, 17}, {9, SHIFT, 18}, {23, SHIFT, 31}, {26, SHIFT, 20}, },
			{{-1, ERROR, 25}, {3, SHIFT, 16}, {23, SHIFT, 34}, },
			{{-1, ERROR, 26}, {7, SHIFT, 36}, },
			{{-1, ERROR, 27}, {3, SHIFT, 16}, {8, SHIFT, 17}, {9, SHIFT, 18}, {23, SHIFT, 37}, {26, SHIFT, 20}, },
			{{-1, ERROR, 28}, {26, SHIFT, 40}, },
			{{-1, ERROR, 29}, {21, SHIFT, 41}, },
			{{-1, ERROR, 30}, {15, SHIFT, 42}, },
			{{-1, REDUCE, 4}, },
			{{-1, REDUCE, 68}, },
			{{-1, ERROR, 33}, {3, SHIFT, 16}, {23, SHIFT, 43}, },
			{{-1, REDUCE, 5}, },
			{{-1, REDUCE, 70}, },
			{{-1, ERROR, 36}, {20, SHIFT, 44}, },
			{{-1, REDUCE, 7}, },
			{{-1, ERROR, 38}, {3, SHIFT, 16}, {8, SHIFT, 17}, {9, SHIFT, 18}, {23, SHIFT, 45}, {26, SHIFT, 20}, },
			{{-1, ERROR, 39}, {3, SHIFT, 16}, {23, SHIFT, 47}, },
			{{-1, ERROR, 40}, {24, SHIFT, 48}, },
			{{-1, REDUCE, 21}, },
			{{-1, REDUCE, 11}, },
			{{-1, REDUCE, 6}, },
			{{-1, ERROR, 44}, {21, SHIFT, 49}, },
			{{-1, REDUCE, 8}, },
			{{-1, ERROR, 46}, {3, SHIFT, 16}, {23, SHIFT, 50}, },
			{{-1, REDUCE, 9}, },
			{{-1, REDUCE, 18}, {8, SHIFT, 17}, {9, SHIFT, 18}, {26, SHIFT, 20}, },
			{{-1, ERROR, 49}, {26, SHIFT, 54}, },
			{{-1, REDUCE, 10}, },
			{{-1, ERROR, 51}, {25, SHIFT, 55}, },
			{{-1, REDUCE, 16}, {16, SHIFT, 56}, },
			{{-1, ERROR, 53}, {26, SHIFT, 59}, },
			{{-1, ERROR, 54}, {25, SHIFT, 60}, },
			{{-1, ERROR, 55}, {22, SHIFT, 61}, },
			{{-1, ERROR, 56}, {8, SHIFT, 17}, {9, SHIFT, 18}, {26, SHIFT, 20}, },
			{{-1, REDUCE, 73}, },
			{{-1, REDUCE, 17}, {16, SHIFT, 56}, },
			{{-1, REDUCE, 19}, },
			{{-1, ERROR, 60}, {22, SHIFT, 64}, },
			{{-1, ERROR, 61}, {4, SHIFT, 65}, {8, SHIFT, 17}, {9, SHIFT, 18}, {10, SHIFT, 66}, {12, SHIFT, 67}, {13, SHIFT, 68}, {22, SHIFT, 69}, {26, SHIFT, 70}, },
			{{-1, ERROR, 62}, {26, SHIFT, 75}, },
			{{-1, REDUCE, 74}, },
			{{-1, ERROR, 64}, {10, SHIFT, 66}, {12, SHIFT, 67}, {13, SHIFT, 68}, {22, SHIFT, 69}, {26, SHIFT, 76}, },
			{{-1, ERROR, 65}, {5, SHIFT, 78}, {6, SHIFT, 79}, {18, SHIFT, 80}, {19, SHIFT, 81}, {24, SHIFT, 82}, {26, SHIFT, 83}, {27, SHIFT, 84}, {34, SHIFT, 85}, },
			{{-1, ERROR, 66}, {24, SHIFT, 94}, },
			{{-1, ERROR, 67}, {24, SHIFT, 95}, },
			{{-1, ERROR, 68}, {24, SHIFT, 96}, },
			{{-1, ERROR, 69}, {10, SHIFT, 66}, {12, SHIFT, 67}, {13, SHIFT, 68}, {22, SHIFT, 69}, {23, SHIFT, 97}, {26, SHIFT, 76}, },
			{{-1, REDUCE, 24}, {17, SHIFT, 99}, {20, SHIFT, 100}, },
			{{-1, REDUCE, 71}, },
			{{-1, REDUCE, 25}, },
			{{-1, ERROR, 73}, {4, SHIFT, 101}, {8, SHIFT, 17}, {9, SHIFT, 18}, {10, SHIFT, 66}, {12, SHIFT, 67}, {13, SHIFT, 68}, {22, SHIFT, 69}, {26, SHIFT, 70}, },
			{{-1, ERROR, 74}, {4, SHIFT, 103}, {10, SHIFT, 66}, {12, SHIFT, 67}, {13, SHIFT, 68}, {22, SHIFT, 69}, {26, SHIFT, 76}, },
			{{-1, REDUCE, 20}, },
			{{-1, ERROR, 76}, {17, SHIFT, 99}, {20, SHIFT, 100}, },
			{{-1, ERROR, 77}, {23, SHIFT, 105}, },
			{{-1, REDUCE, 57}, },
			{{-1, ERROR, 79}, {8, SHIFT, 106}, {26, SHIFT, 107}, },
			{{-1, REDUCE, 54}, },
			{{-1, REDUCE, 55}, },
			{{-1, ERROR, 82}, {5, SHIFT, 78}, {6, SHIFT, 79}, {18, SHIFT, 80}, {19, SHIFT, 81}, {24, SHIFT, 82}, {26, SHIFT, 83}, {27, SHIFT, 84}, {34, SHIFT, 85}, },
			{{-1, REDUCE, 56}, },
			{{-1, REDUCE, 53}, },
			{{-1, ERROR, 85}, {5, SHIFT, 78}, {6, SHIFT, 79}, {18, SHIFT, 80}, {19, SHIFT, 81}, {24, SHIFT, 82}, {26, SHIFT, 83}, {27, SHIFT, 84}, {34, SHIFT, 85}, },
			{{-1, ERROR, 86}, {15, SHIFT, 110}, {29, SHIFT, 111}, },
			{{-1, REDUCE, 38}, {28, SHIFT, 112}, },
			{{-1, REDUCE, 40}, {30, SHIFT, 113}, {31, SHIFT, 114}, },
			{{-1, REDUCE, 43}, {32, SHIFT, 115}, },
			{{-1, REDUCE, 45}, },
			{{-1, REDUCE, 47}, {33, SHIFT, 116}, },
			{{-1, REDUCE, 50}, },
			{{-1, REDUCE, 52}, {20, SHIFT, 117}, },
			{{-1, ERROR, 94}, {5, SHIFT, 78}, {6, SHIFT, 79}, {18, SHIFT, 80}, {19, SHIFT, 81}, {24, SHIFT, 82}, {26, SHIFT, 83}, {27, SHIFT, 84}, {34, SHIFT, 85}, },
			{{-1, ERROR, 95}, {5, SHIFT, 78}, {6, SHIFT, 79}, {18, SHIFT, 80}, {19, SHIFT, 81}, {24, SHIFT, 82}, {26, SHIFT, 83}, {27, SHIFT, 84}, {34, SHIFT, 85}, },
			{{-1, ERROR, 96}, {5, SHIFT, 78}, {6, SHIFT, 79}, {18, SHIFT, 80}, {19, SHIFT, 81}, {24, SHIFT, 82}, {26, SHIFT, 83}, {27, SHIFT, 84}, {34, SHIFT, 85}, },
			{{-1, REDUCE, 29}, },
			{{-1, ERROR, 98}, {10, SHIFT, 66}, {12, SHIFT, 67}, {13, SHIFT, 68}, {22, SHIFT, 69}, {23, SHIFT, 121}, {26, SHIFT, 76}, },
			{{-1, ERROR, 99}, {5, SHIFT, 78}, {6, SHIFT, 79}, {18, SHIFT, 80}, {19, SHIFT, 81}, {24, SHIFT, 82}, {26, SHIFT, 83}, {27, SHIFT, 84}, {34, SHIFT, 85}, },
			{{-1, ERROR, 100}, {5, SHIFT, 78}, {6, SHIFT, 79}, {18, SHIFT, 80}, {19, SHIFT, 81}, {24, SHIFT, 82}, {26, SHIFT, 83}, {27, SHIFT, 84}, {34, SHIFT, 85}, },
			{{-1, ERROR, 101}, {5, SHIFT, 78}, {6, SHIFT, 79}, {18, SHIFT, 80}, {19, SHIFT, 81}, {24, SHIFT, 82}, {26, SHIFT, 83}, {27, SHIFT, 84}, {34, SHIFT, 85}, },
			{{-1, ERROR, 102}, {4, SHIFT, 125}, {10, SHIFT, 66}, {12, SHIFT, 67}, {13, SHIFT, 68}, {22, SHIFT, 69}, {26, SHIFT, 76}, },
			{{-1, ERROR, 103}, {5, SHIFT, 78}, {6, SHIFT, 79}, {18, SHIFT, 80}, {19, SHIFT, 81}, {24, SHIFT, 82}, {26, SHIFT, 83}, {27, SHIFT, 84}, {34, SHIFT, 85}, },
			{{-1, REDUCE, 72}, },
			{{-1, ERROR, 105}, {23, SHIFT, 127}, },
			{{-1, ERROR, 106}, {20, SHIFT, 128}, },
			{{-1, ERROR, 107}, {24, SHIFT, 129}, },
			{{-1, ERROR, 108}, {25, SHIFT, 130}, {29, SHIFT, 111}, },
			{{-1, REDUCE, 46}, },
			{{-1, ERROR, 110}, {23, SHIFT, 131}, },
			{{-1, ERROR, 111}, {5, SHIFT, 78}, {6, SHIFT, 79}, {18, SHIFT, 80}, {19, SHIFT, 81}, {24, SHIFT, 82}, {26, SHIFT, 83}, {27, SHIFT, 84}, {34, SHIFT, 85}, },
			{{-1, ERROR, 112}, {5, SHIFT, 78}, {6, SHIFT, 79}, {18, SHIFT, 80}, {19, SHIFT, 81}, {24, SHIFT, 82}, {26, SHIFT, 83}, {27, SHIFT, 84}, {34, SHIFT, 85}, },
			{{-1, ERROR, 113}, {5, SHIFT, 78}, {6, SHIFT, 79}, {18, SHIFT, 80}, {19, SHIFT, 81}, {24, SHIFT, 82}, {26, SHIFT, 83}, {27, SHIFT, 84}, {34, SHIFT, 85}, },
			{{-1, ERROR, 114}, {5, SHIFT, 78}, {6, SHIFT, 79}, {18, SHIFT, 80}, {19, SHIFT, 81}, {24, SHIFT, 82}, {26, SHIFT, 83}, {27, SHIFT, 84}, {34, SHIFT, 85}, },
			{{-1, ERROR, 115}, {5, SHIFT, 78}, {6, SHIFT, 79}, {18, SHIFT, 80}, {19, SHIFT, 81}, {24, SHIFT, 82}, {26, SHIFT, 83}, {27, SHIFT, 84}, {34, SHIFT, 85}, },
			{{-1, ERROR, 116}, {14, SHIFT, 137}, {26, SHIFT, 138}, },
			{{-1, ERROR, 117}, {5, SHIFT, 78}, {6, SHIFT, 79}, {18, SHIFT, 80}, {19, SHIFT, 81}, {24, SHIFT, 82}, {26, SHIFT, 83}, {27, SHIFT, 84}, {34, SHIFT, 85}, },
			{{-1, ERROR, 118}, {25, SHIFT, 140}, {29, SHIFT, 111}, },
			{{-1, ERROR, 119}, {25, SHIFT, 141}, {29, SHIFT, 111}, },
			{{-1, ERROR, 120}, {25, SHIFT, 142}, {29, SHIFT, 111}, },
			{{-1, REDUCE, 30}, },
			{{-1, ERROR, 122}, {15, SHIFT, 143}, {29, SHIFT, 111}, },
			{{-1, ERROR, 123}, {21, SHIFT, 144}, {29, SHIFT, 111}, },
			{{-1, ERROR, 124}, {15, SHIFT, 145}, {29, SHIFT, 111}, },
			{{-1, ERROR, 125}, {5, SHIFT, 78}, {6, SHIFT, 79}, {18, SHIFT, 80}, {19, SHIFT, 81}, {24, SHIFT, 82}, {26, SHIFT, 83}, {27, SHIFT, 84}, {34, SHIFT, 85}, },
			{{-1, ERROR, 126}, {15, SHIFT, 147}, {29, SHIFT, 111}, },
			{{-1, REDUCE, 2}, },
			{{-1, ERROR, 128}, {5, SHIFT, 78}, {6, SHIFT, 79}, {18, SHIFT, 80}, {19, SHIFT, 81}, {24, SHIFT, 82}, {26, SHIFT, 83}, {27, SHIFT, 84}, {34, SHIFT, 85}, },
			{{-1, ERROR, 129}, {25, SHIFT, 149}, },
			{{-1, REDUCE, 60}, },
			{{-1, REDUCE, 12}, },
			{{-1, REDUCE, 37}, {28, SHIFT, 112}, },
			{{-1, REDUCE, 39}, {30, SHIFT, 113}, {31, SHIFT, 114}, },
			{{-1, REDUCE, 41}, {32, SHIFT, 115}, },
			{{-1, REDUCE, 42}, {32, SHIFT, 115}, },
			{{-1, REDUCE, 44}, },
			{{-1, REDUCE, 48}, },
			{{-1, ERROR, 138}, {24, SHIFT, 150}, },
			{{-1, ERROR, 139}, {21, SHIFT, 151}, {29, SHIFT, 111}, },
			{{-1, ERROR, 140}, {10, SHIFT, 152}, {12, SHIFT, 153}, {13, SHIFT, 68}, {22, SHIFT, 69}, {26, SHIFT, 76}, },
			{{-1, ERROR, 141}, {10, SHIFT, 66}, {12, SHIFT, 67}, {13, SHIFT, 68}, {22, SHIFT, 69}, {26, SHIFT, 76}, },
			{{-1, ERROR, 142}, {15, SHIFT, 158}, },
			{{-1, REDUCE, 32}, },
			{{-1, ERROR, 144}, {17, SHIFT, 159}, },
			{{-1, ERROR, 145}, {23, SHIFT, 160}, },
			{{-1, ERROR, 146}, {15, SHIFT, 161}, {29, SHIFT, 111}, },
			{{-1, ERROR, 147}, {23, SHIFT, 162}, },
			{{-1, ERROR, 148}, {21, SHIFT, 163}, {29, SHIFT, 111}, },
			{{-1, REDUCE, 59}, },
			{{-1, REDUCE, 63}, {5, SHIFT, 78}, {6, SHIFT, 79}, {18, SHIFT, 80}, {19, SHIFT, 81}, {24, SHIFT, 82}, {26, SHIFT, 83}, {27, SHIFT, 84}, {34, SHIFT, 85}, },
			{{-1, REDUCE, 51}, },
			{{-1, ERROR, 152}, {24, SHIFT, 166}, },
			{{-1, ERROR, 153}, {24, SHIFT, 167}, },
			{{-1, REDUCE, 26}, },
			{{-1, REDUCE, 25}, {11, REDUCE, 34}, },
			{{-1, ERROR, 156}, {11, SHIFT, 168}, },
			{{-1, REDUCE, 28}, },
			{{-1, REDUCE, 31}, },
			{{-1, ERROR, 159}, {5, SHIFT, 78}, {6, SHIFT, 79}, {18, SHIFT, 80}, {19, SHIFT, 81}, {24, SHIFT, 82}, {26, SHIFT, 83}, {27, SHIFT, 84}, {34, SHIFT, 85}, },
			{{-1, REDUCE, 13}, },
			{{-1, ERROR, 161}, {23, SHIFT, 170}, },
			{{-1, REDUCE, 14}, },
			{{-1, REDUCE, 58}, },
			{{-1, REDUCE, 61}, {16, SHIFT, 171}, {29, SHIFT, 111}, },
			{{-1, ERROR, 165}, {25, SHIFT, 174}, },
			{{-1, ERROR, 166}, {5, SHIFT, 78}, {6, SHIFT, 79}, {18, SHIFT, 80}, {19, SHIFT, 81}, {24, SHIFT, 82}, {26, SHIFT, 83}, {27, SHIFT, 84}, {34, SHIFT, 85}, },
			{{-1, ERROR, 167}, {5, SHIFT, 78}, {6, SHIFT, 79}, {18, SHIFT, 80}, {19, SHIFT, 81}, {24, SHIFT, 82}, {26, SHIFT, 83}, {27, SHIFT, 84}, {34, SHIFT, 85}, },
			{{-1, ERROR, 168}, {10, SHIFT, 66}, {12, SHIFT, 67}, {13, SHIFT, 68}, {22, SHIFT, 69}, {26, SHIFT, 76}, },
			{{-1, ERROR, 169}, {15, SHIFT, 178}, {29, SHIFT, 111}, },
			{{-1, REDUCE, 15}, },
			{{-1, ERROR, 171}, {5, SHIFT, 78}, {6, SHIFT, 79}, {18, SHIFT, 80}, {19, SHIFT, 81}, {24, SHIFT, 82}, {26, SHIFT, 83}, {27, SHIFT, 84}, {34, SHIFT, 85}, },
			{{-1, REDUCE, 75}, },
			{{-1, REDUCE, 62}, {16, SHIFT, 171}, },
			{{-1, REDUCE, 49}, },
			{{-1, ERROR, 175}, {25, SHIFT, 181}, {29, SHIFT, 111}, },
			{{-1, ERROR, 176}, {25, SHIFT, 182}, {29, SHIFT, 111}, },
			{{-1, REDUCE, 27}, },
			{{-1, REDUCE, 33}, },
			{{-1, REDUCE, 64}, {29, SHIFT, 111}, },
			{{-1, REDUCE, 76}, },
			{{-1, ERROR, 181}, {10, SHIFT, 152}, {12, SHIFT, 153}, {13, SHIFT, 68}, {22, SHIFT, 69}, {26, SHIFT, 76}, },
			{{-1, ERROR, 182}, {10, SHIFT, 152}, {12, SHIFT, 153}, {13, SHIFT, 68}, {22, SHIFT, 69}, {26, SHIFT, 76}, },
			{{-1, ERROR, 183}, {11, SHIFT, 185}, },
			{{-1, REDUCE, 35}, },
			{{-1, ERROR, 185}, {10, SHIFT, 152}, {12, SHIFT, 153}, {13, SHIFT, 68}, {22, SHIFT, 69}, {26, SHIFT, 76}, },
			{{-1, REDUCE, 36}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 2}, },
			{{-1, 3}, },
			{{-1, 6}, {7, 10}, },
			{{-1, 21}, {24, 32}, {38, 32}, {73, 32}, },
			{{-1, 22}, {25, 35}, {33, 35}, {39, 35}, {46, 35}, },
			{{-1, 51}, },
			{{-1, 52}, },
			{{-1, 57}, {58, 63}, },
			{{-1, 23}, {16, 28}, {48, 53}, {56, 62}, },
			{{-1, 71}, {64, 77}, {74, 104}, {98, 104}, {102, 104}, {140, 154}, {141, 157}, {168, 177}, {181, 154}, {182, 157}, {185, 177}, },
			{{-1, 72}, {140, 155}, {181, 155}, {182, 155}, {185, 155}, },
			{{-1, 156}, {181, 183}, {182, 184}, {185, 186}, },
			{{-1, 86}, {82, 108}, {94, 118}, {95, 119}, {96, 120}, {99, 122}, {100, 123}, {101, 124}, {103, 126}, {117, 139}, {125, 146}, {128, 148}, {150, 164}, {159, 169}, {166, 175}, {167, 176}, {171, 179}, },
			{{-1, 87}, {111, 132}, },
			{{-1, 88}, {112, 133}, },
			{{-1, 89}, {113, 134}, {114, 135}, },
			{{-1, 90}, {85, 109}, {115, 136}, },
			{{-1, 91}, },
			{{-1, 92}, },
			{{-1, 93}, },
			{{-1, 165}, },
			{{-1, 172}, {173, 180}, },
			{{-1, 7}, },
			{{-1, 24}, {27, 38}, {61, 73}, },
			{{-1, 25}, {24, 33}, {27, 39}, {38, 46}, },
			{{-1, 74}, {69, 98}, {73, 102}, },
			{{-1, 58}, },
			{{-1, 173}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: 'class'",
			"expecting: id",
			"expecting: EOF",
			"expecting: 'class', EOF",
			"expecting: '{'",
			"expecting: 'public'",
			"expecting: 'extends', '{'",
			"expecting: 'static void main'",
			"expecting: 'public', 'int', 'boolean', '}', id",
			"expecting: '('",
			"expecting: 'int', 'boolean', id",
			"expecting: '[', id",
			"expecting: 'public', 'return', 'int', 'boolean', 'if', 'while', 'System.out.println', '{', '}', id",
			"expecting: 'public', '}'",
			"expecting: 'String'",
			"expecting: ']'",
			"expecting: ';'",
			"expecting: '['",
			"expecting: 'int', 'boolean', ')', id",
			"expecting: ')'",
			"expecting: ',', ')'",
			"expecting: 'return', 'int', 'boolean', 'if', 'while', 'System.out.println', '{', id",
			"expecting: 'if', 'while', 'System.out.println', '{', id",
			"expecting: 'this', 'new', 'true', 'false', '(', id, integer, '!'",
			"expecting: 'if', 'while', 'System.out.println', '{', '}', id",
			"expecting: '=', '[', id",
			"expecting: 'return', 'if', 'while', 'System.out.println', '{', '}', id",
			"expecting: 'return', 'if', 'while', 'System.out.println', '{', id",
			"expecting: '=', '['",
			"expecting: '}'",
			"expecting: ';', ',', '[', ']', ')', '<', '&&', '+', '-', '*', '.'",
			"expecting: 'int', id",
			"expecting: ';', '&&'",
			"expecting: ';', ',', ']', ')', '<', '&&'",
			"expecting: ';', ',', ']', ')', '<', '&&', '+', '-'",
			"expecting: ';', ',', ']', ')', '<', '&&', '+', '-', '*'",
			"expecting: ';', ',', ']', ')', '<', '&&', '+', '-', '*', '.'",
			"expecting: 'return', 'if', 'else', 'while', 'System.out.println', '{', '}', id",
			"expecting: ')', '&&'",
			"expecting: 'length', id",
			"expecting: ']', '&&'",
			"expecting: '='",
			"expecting: 'this', 'new', 'true', 'false', '(', ')', id, integer, '!'",
			"expecting: 'else'",
			"expecting: ',', ')', '&&'",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 3, 4, 1, 3, 3, 5, 6, 3, 7, 1, 8, 9, 4, 10, 11, 1, 3, 1, 12, 13, 1, 8, 13, 14, 8, 1, 15, 16, 3, 12, 13, 3, 13, 17, 3, 8, 13, 9, 1, 12, 3, 15, 3, 13, 3, 18, 1, 3, 19, 20, 1, 19, 4, 10, 20, 20, 20, 4, 21, 1, 20, 22, 23, 9, 9, 9, 24, 25, 26, 26, 21, 27, 20, 28, 29, 30, 31, 30, 30, 23, 30, 30, 23, 32, 33, 34, 35, 35, 36, 36, 30, 23, 23, 23, 37, 24, 23, 23, 23, 27, 23, 26, 29, 17, 9, 38, 35, 29, 23, 23, 23, 23, 23, 39, 23, 38, 38, 38, 37, 32, 40, 32, 23, 32, 3, 23, 19, 30, 13, 33, 34, 35, 35, 35, 36, 9, 40, 22, 22, 16, 37, 41, 29, 32, 29, 40, 30, 42, 36, 9, 9, 26, 37, 43, 26, 37, 23, 13, 29, 13, 30, 44, 19, 23, 23, 22, 32, 13, 23, 20, 20, 36, 38, 38, 26, 37, 44, 20, 22, 22, 43, 43, 22, 43, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            Parser.actionTable = new int[length][][];
            for(int i = 0; i < Parser.actionTable.length; i++)
            {
                length = s.readInt();
                Parser.actionTable[i] = new int[length][3];
                for(int j = 0; j < Parser.actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    Parser.actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
