/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import minijava.analysis.*;

@SuppressWarnings("nls")
public final class AIfStatement extends PStatement
{
    private PExp _condition_;
    private PStatement _ifstm_;
    private PStatement _elsestm_;

    public AIfStatement()
    {
        // Constructor
    }

    public AIfStatement(
        @SuppressWarnings("hiding") PExp _condition_,
        @SuppressWarnings("hiding") PStatement _ifstm_,
        @SuppressWarnings("hiding") PStatement _elsestm_)
    {
        // Constructor
        setCondition(_condition_);

        setIfstm(_ifstm_);

        setElsestm(_elsestm_);

    }

    @Override
    public Object clone()
    {
        return new AIfStatement(
            cloneNode(this._condition_),
            cloneNode(this._ifstm_),
            cloneNode(this._elsestm_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfStatement(this);
    }

    public PExp getCondition()
    {
        return this._condition_;
    }

    public void setCondition(PExp node)
    {
        if(this._condition_ != null)
        {
            this._condition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._condition_ = node;
    }

    public PStatement getIfstm()
    {
        return this._ifstm_;
    }

    public void setIfstm(PStatement node)
    {
        if(this._ifstm_ != null)
        {
            this._ifstm_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ifstm_ = node;
    }

    public PStatement getElsestm()
    {
        return this._elsestm_;
    }

    public void setElsestm(PStatement node)
    {
        if(this._elsestm_ != null)
        {
            this._elsestm_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._elsestm_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._condition_)
            + toString(this._ifstm_)
            + toString(this._elsestm_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._condition_ == child)
        {
            this._condition_ = null;
            return;
        }

        if(this._ifstm_ == child)
        {
            this._ifstm_ = null;
            return;
        }

        if(this._elsestm_ == child)
        {
            this._elsestm_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._condition_ == oldChild)
        {
            setCondition((PExp) newChild);
            return;
        }

        if(this._ifstm_ == oldChild)
        {
            setIfstm((PStatement) newChild);
            return;
        }

        if(this._elsestm_ == oldChild)
        {
            setElsestm((PStatement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
